# Generated by Django 5.1.3 on 2024-11-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('rockerboy', 'Rockerboy'), ('solo', 'Solo'), ('netrunner', 'Netrunner'), ('tech', 'Tech'), ('medtech', 'Medtech'), ('exec', 'Exec'), ('lawman', 'Lawman'), ('fixer', 'Fixer'), ('nomad', 'Nomad')], max_length=50)),
                ('cultural_origin', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
